[metadata]
name = martini_mapper
version = 0.1.0
description = Martini Mapper
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT

[options]
packages =
    martini_mapper
include_package_data = True
python_requires = >=3.10

# If you prefer to keep dependencies in requirements.txt, you can remove
# install_requires entirely. Otherwise list runtime deps here.
install_requires =
    numpy
    pandas
    scipy
    scikit-learn
    rdkit
    mdtraj

